In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.metrics import recall_score, precision_score, roc_auc_score, accuracy_score,confusion_matrix,average_precision_score,f1_score

In [31]:
df=pd.read_csv("E:/financial fraud detection/data/creditcard.csv")

In [33]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [34]:
df.shape

(284807, 31)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [36]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [37]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [38]:
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Count transactions by class
# print(df['Class'].value_counts())

# # Plot
# sns.countplot(x='Class', data=df)
# plt.title('Fraud vs Legitimate Transactions')
# plt.xlabel('Class (0 = Legitimate, 1 = Fraud)')
# plt.ylabel('Number of Transactions')
# plt.show()

In [39]:
class_percentage = df['Class'].value_counts(normalize=True) * 100

print(class_percentage)

Class
0    99.827251
1     0.172749
Name: proportion, dtype: float64

In [40]:
# plt.figure(figsize=(10, 5))

# sns.boxplot(x='Class', y='Amount', data=df)

# plt.title('Transaction Amount: Fraud vs Legitimate')
# plt.xlabel('Class (0 = Legitimate, 1 = Fraud)')
# plt.ylabel('Transaction Amount')
# plt.show()

In [41]:
# import numpy as np

# df['Amount_log'] = np.log1p(df['Amount'])

# plt.figure(figsize=(10, 5))

# sns.boxplot(x='Class', y='Amount_log', data=df)

# plt.title('Transaction Amount Distribution (Log Scale)')
# plt.xlabel('Class (0 = Legitimate, 1 = Fraud)')
# plt.ylabel('Log(Transaction Amount + 1)')
# plt.show()

In [42]:
# Correlation with Class
correlation = df.corr()['Class'].sort_values()

print(correlation)

V17      -0.326481
V14      -0.302544
V12      -0.260593
V10      -0.216883
V16      -0.196539
V3       -0.192961
V7       -0.187257
V18      -0.111485
V1       -0.101347
V9       -0.097733
V5       -0.094974
V6       -0.043643
Time     -0.012323
V24      -0.007221
V13      -0.004570
V15      -0.004223
V23      -0.002685
V22       0.000805
V25       0.003308
V26       0.004455
Amount    0.005632
V28       0.009536
V27       0.017580
V8        0.019875
V20       0.020090
V19       0.034783
V21       0.040413
V2        0.091289
V4        0.133447
V11       0.154876
Class     1.000000
Name: Class, dtype: float64

In [43]:
# plt.figure(figsize=(14, 10))

# sns.heatmap(
#     df.corr(),
#     cmap='coolwarm',
#     linewidths=0.1
# )

# plt.title('Correlation Heatmap')
# plt.show()

In [44]:
# features = ['V4', 'V10', 'V12', 'V14', 'V17']

# for feature in features:
#     plt.figure(figsize=(8, 4))
    
#     sns.boxplot(x='Class', y=feature, data=df)
    
#     plt.title(f'{feature}: Fraud vs Legitimate')
#     plt.xlabel('Class (0 = Legitimate, 1 = Fraud)')
#     plt.ylabel(feature)
    
#     plt.show()

In [45]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [46]:
x=df.drop('Class',axis=1)
y=df['Class']

In [47]:
x.shape

(284807, 30)

In [48]:
y.shape

(284807,)

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [50]:
lr_pipeline=Pipeline(steps=[
    ('scaler',StandardScaler()),
    ('model',LogisticRegression(class_weight='balanced',
                                max_iter=1000))
])

In [51]:
rf_pipeline=Pipeline(steps=[
    ('model',RandomForestClassifier(
        n_estimators=100,
        class_weight='balanced',
        n_jobs=-1
    ))
])

In [52]:
lr_pipeline.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [53]:
rf_pipeline.fit(x_train,y_train)

Pipeline(steps=[('model',
                 RandomForestClassifier(class_weight='balanced', n_jobs=-1))])

In [54]:
y_pred_lr = lr_pipeline.predict(x_test)
y_prob_lr = lr_pipeline.predict_proba(x_test)[:, 1]
y_pred_lr,y_prob_lr

(array([1, 0, 0, ..., 0, 0, 0], shape=(85443,)),
 array([1.        , 0.03210611, 0.0182031 , ..., 0.2530621 , 0.05461532,
        0.11739396], shape=(85443,)))

In [55]:
y_pred_rf = rf_pipeline.predict(x_test)
y_prob_rf = rf_pipeline.predict_proba(x_test)[:, 1]
y_pred_rf,y_prob_rf

(array([1, 0, 0, ..., 0, 0, 0], shape=(85443,)),
 array([0.99, 0.  , 0.  , ..., 0.  , 0.  , 0.  ], shape=(85443,)))

In [56]:
cm_lr = confusion_matrix(y_test, y_pred_lr)
cm_rf = confusion_matrix(y_test, y_pred_rf)

print("Logistic Regression:")
print(cm_lr)

print("\nRandom Forest:")
print(cm_rf)

Logistic Regression:
[[83154  2153]
 [   10   126]]

Random Forest:
[[85296    11]
 [   25   111]]

In [57]:
from sklearn.metrics import classification_report

print("===== Logistic Regression =====")
print(classification_report(y_test, y_pred_lr))

print("===== Random Forest =====")
print(classification_report(y_test, y_pred_rf))

===== Logistic Regression =====
              precision    recall  f1-score   support

           0       1.00      0.97      0.99     85307
           1       0.06      0.93      0.10       136

    accuracy                           0.97     85443
   macro avg       0.53      0.95      0.55     85443
weighted avg       1.00      0.97      0.99     85443

===== Random Forest =====
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.91      0.82      0.86       136

    accuracy                           1.00     85443
   macro avg       0.95      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443

In [58]:


roc_lr = roc_auc_score(y_test, y_prob_lr)
pr_lr = average_precision_score(y_test, y_prob_lr)

roc_rf = roc_auc_score(y_test, y_prob_rf)
pr_rf = average_precision_score(y_test, y_prob_rf)

print("Logistic Regression")
print("ROC-AUC:", roc_lr)
print("PR-AUC:", pr_lr)

print("\nRandom Forest")
print("ROC-AUC:", roc_rf)
print("PR-AUC:", pr_rf)

Logistic Regression
ROC-AUC: 0.9820193105317196
PR-AUC: 0.7516433137090945

Random Forest
ROC-AUC: 0.968542509786453
PR-AUC: 0.8785855424424388

In [59]:
rf_pipeline.predict(x_test)

array([1, 0, 0, ..., 0, 0, 0], shape=(85443,))

In [60]:
thresholds = [0.1, 0.2, 0.3, 0.4, 0.5]

for threshold in thresholds:
    y_pred_threshold = (y_prob_rf >= threshold).astype(int)

    precision = precision_score(y_test, y_pred_threshold)
    recall = recall_score(y_test, y_pred_threshold)
    f1 = f1_score(y_test, y_pred_threshold)

    print(f"Threshold: {threshold}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall:    {recall:.2f}")
    print(f"F1-score:  {f1:.2f}")
    print("-" * 30)

Threshold: 0.1
Precision: 0.59
Recall:    0.90
F1-score:  0.71
------------------------------
Threshold: 0.2
Precision: 0.74
Recall:    0.89
F1-score:  0.81
------------------------------
Threshold: 0.3
Precision: 0.84
Recall:    0.88
F1-score:  0.86
------------------------------
Threshold: 0.4
Precision: 0.88
Recall:    0.85
F1-score:  0.87
------------------------------
Threshold: 0.5
Precision: 0.90
Recall:    0.82
F1-score:  0.86
------------------------------

In [61]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20],
    'min_samples_leaf': [1, 2]
}

In [62]:
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring='f1',
    cv=2,
    n_jobs=-1,
    verbose=2
)

In [63]:
grid_search.fit(x_train, y_train)

Fitting 2 folds for each of 8 candidates, totalling 16 fits

GridSearchCV(cv=2,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [10, 20], 'min_samples_leaf': [1, 2],
                         'n_estimators': [100, 200]},
             scoring='f1', verbose=2)

In [64]:
print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest F1 Score:")
print(grid_search.best_score_)

Best Parameters:
{'max_depth': 20, 'min_samples_leaf': 2, 'n_estimators': 200}

Best F1 Score:
0.8232240363665707

In [65]:
best_rf = grid_search.best_estimator_

In [66]:
from sklearn.ensemble import RandomForestClassifier

final_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

final_model.fit(x_train, y_train)

print("Final model trained successfully!")

Final model trained successfully!

In [67]:
import joblib

joblib.dump(final_model, 'fraud_detection_model.pkl')

print("Model saved successfully!")

Model saved successfully!

In [69]:
# Remove the target column
test_data = df.drop('Class', axis=1)

# Select one legitimate transaction
legitimate = test_data[df['Class'] == 0].sample(
    1, random_state=42
)

# Select one fraudulent transaction
fraud = test_data[df['Class'] == 1].sample(
    1, random_state=42
)

print("LEGITIMATE TRANSACTION")
display(legitimate)

print("FRAUDULENT TRANSACTION")
display(fraud)

LEGITIMATE TRANSACTION

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
138028,82450.0,1.314539,0.590643,-0.666593,0.716564,0.301978,-1.125467,0.388881,-0.28839,-0.132137,...,-0.05804,-0.170307,-0.429655,-0.141341,-0.200195,0.639491,0.399476,-0.034321,0.031692,0.76

FRAUDULENT TRANSACTION

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
17407,28692.0,-29.200329,16.155701,-30.013712,6.476731,-21.22581,-4.902997,-19.791248,19.168327,-3.617242,...,1.715862,1.809371,-2.175815,-1.365104,0.174286,2.103868,-0.209944,1.278681,0.372393,99.99

In [70]:
import joblib

# Load the saved model
model = joblib.load("fraud_detection_model.pkl")

# Predict legitimate transaction
legitimate_prediction = model.predict(legitimate)[0]
legitimate_probability = model.predict_proba(legitimate)[0][1]

# Predict fraudulent transaction
fraud_prediction = model.predict(fraud)[0]
fraud_probability = model.predict_proba(fraud)[0][1]

print("LEGITIMATE TRANSACTION")
print("Prediction:", "FRAUD" if legitimate_prediction == 1 else "LEGITIMATE")
print("Fraud Probability:", f"{legitimate_probability * 100:.2f}%")

print("\nFRAUDULENT TRANSACTION")
print("Prediction:", "FRAUD" if fraud_prediction == 1 else "LEGITIMATE")
print("Fraud Probability:", f"{fraud_probability * 100:.2f}%")

LEGITIMATE TRANSACTION
Prediction: LEGITIMATE
Fraud Probability: 0.00%

FRAUDULENT TRANSACTION
Prediction: FRAUD
Fraud Probability: 100.00%